Merge kernel-1 into master

diff --git a/tests/0112/run b/tests/0112/run
--- a/tests/0112/run
+++ b/tests/0112/run
@@ -1,4 +1,5 @@
-# Test ZUK
+echo "0112 - ZUK"
+
 . ../tests/common.sh
 
 cat > tmp.$$.orbs.txt << EOT
@@ -9,8 +10,8 @@ integer matrix rows=1 cols=24
 EOT
 zcv -Q tmp.$$.orbs.txt tmp.$$.orbs || error "ZCV failed"
 for f in $TEST_FIELDS ; do
-    zuk -Q ../tests/data/Mat$f tmp.$$.orbs tmp.$$.x || error "ZUK failed"
-    cmp ../tests/data/Mat$f tmp.$$.x || error "ZUK with trivial orbits: wrong result"
+    zuk -Q "${MTX_TEST_DATA_DIR}/Mat$f" tmp.$$.orbs tmp.$$.x || error "ZUK failed"
+    cmp "${MTX_TEST_DATA_DIR}/Mat$f" tmp.$$.x || error "ZUK with trivial orbits: wrong result"
 done
 
 
@@ -22,17 +23,10 @@ integer matrix rows=1 cols=24
 EOT
 zcv -Q tmp.$$.orbs.txt tmp.$$.orbs || error "ZCV failed"
 for f in 2 5 9 25 67 125 256 ; do
-    zuk -Q ../tests/data/Mat$f tmp.$$.orbs tmp.$$.x$f || error "ZUK failed"
+    zuk -Q "${MTX_TEST_DATA_DIR}/Mat$f" tmp.$$.orbs tmp.$$.x$f || error "ZUK failed"
+    zpr tmp.$$.x$f tmp.$$.x$f.txt 
+    cmp tmp.$$.x$f.txt "${MTX_TESTCASE_DIR}/x$f.txt.expected"
 done
-checksum tmp.$$.x2 108.2330969734
-checksum tmp.$$.x5 228.2024623685
-checksum tmp.$$.x9 324.3705451271
-checksum tmp.$$.x25 636.903809115
-checksum tmp.$$.x67 636.518282449
-checksum tmp.$$.x125 636.113758504
-checksum tmp.$$.x256 636.811420983 
 
 # Clean up
-# --------
 rm -f tmp.$$.*
-
diff --git a/tests/0114/run b/tests/0114/run
--- a/tests/0114/run
+++ b/tests/0114/run
@@ -1,15 +1,36 @@
-# Test ZCP
+echo "0114 - ZCP"
 
 . ../tests/common.sh
 
-zcp ../tests/data/ac.1 > tmp.$$.zcp.log || error "ZCP failed"
-zcp -f ../tests/data/ac.1 >> tmp.$$.zcp.log || error "ZCP failed"
-zcp -G ../tests/data/ac.1 >> tmp.$$.zcp.log || error "ZCP failed"
-zcp ../tests/data/ac.2 >> tmp.$$.zcp.log || error "ZCP failed"
-zcp -f ../tests/data/ac.2 >> tmp.$$.zcp.log || error "ZCP failed"
-zcp -G ../tests/data/ac.2 >> tmp.$$.zcp.log || error "ZCP failed"
-checksum tmp.$$.zcp.log 4399.265798641 || exit 1
+#set -x
+
+rm -f tmp.$$.zcp.log
+
+for f in \
+  a5reg.1 a5reg.2 ac.1 ac.2 C0.1 C0.2 m11.1 m11.2 \
+  Mat2 Mat5 Mat9 Mat25 Mat67 Mat125 Mat256 \
+  Ru-K378.1 Ru-K378.2 Ru-K378.3 Ru-K378.4 \
+  Ru-M378.1 Ru-M378.2 \
+  Th-m.1 Th-m.2 Th-m.3 Th-r.1 Th-r.1; do
+   echo "--------------------------------------------------------------------------------" >> tmp.$$.zcp.log
+   echo "----- zcp $f" >> tmp.$$.zcp.log
+   zcp ${MTX_TEST_DATA_DIR}/$f >> tmp.$$.zcp.log || error "ZCP $f failed"
+   echo "----- zcp -f $f" >> tmp.$$.zcp.log
+   zcp -f ${MTX_TEST_DATA_DIR}/$f >> tmp.$$.zcp.log || error "ZCP -f $f failed"
+   echo "----- zcp -m -f $f" >> tmp.$$.zcp.log
+   zcp -m -f ${MTX_TEST_DATA_DIR}/$f >> tmp.$$.zcp.log || error "ZCP -m -f $f failed"
+   echo "----- zcp -G $f" >> tmp.$$.zcp.log
+   zcp -G ${MTX_TEST_DATA_DIR}/$f >> tmp.$$.zcp.log || error "ZCP -G $f failed"
+done
+
+#zcp ${MTX_TEST_DATA_DIR}/ac.1 > tmp.$$.zcp.log || error "ZCP failed"
+#zcp -f ${MTX_TEST_DATA_DIR}/ac.1 >> tmp.$$.zcp.log || error "ZCP failed"
+#zcp -G ${MTX_TEST_DATA_DIR}/ac.1 >> tmp.$$.zcp.log || error "ZCP failed"
+#zcp ${MTX_TEST_DATA_DIR}/ac.2 >> tmp.$$.zcp.log || error "ZCP failed"
+#zcp -f ${MTX_TEST_DATA_DIR}/ac.2 >> tmp.$$.zcp.log || error "ZCP failed"
+#zcp -G ${MTX_TEST_DATA_DIR}/ac.2 >> tmp.$$.zcp.log || error "ZCP failed"
+
+compareWithReference zcp.log
 
 # Clean up
-# --------
 rm -f tmp.$$.*
