Tests refactoring and extension

diff --git a/tests/0112/run b/tests/0112/run
--- a/tests/0112/run
+++ b/tests/0112/run
@@ -2,30 +2,28 @@ echo "0112 - ZUK"
 
 . ../tests/common.sh
 
-cat > tmp.$$.orbs.txt << EOT
+cat > orbs.txt << EOT
 integer matrix rows=1 cols=24
 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 integer matrix rows=1 cols=24
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 EOT
-zcv -Q tmp.$$.orbs.txt tmp.$$.orbs || error "ZCV failed"
+zcv -Q orbs.txt orbs || error "ZCV failed"
 for f in $TEST_FIELDS ; do
-    zuk -Q "${MTX_TEST_DATA_DIR}/Mat$f" tmp.$$.orbs tmp.$$.x || error "ZUK failed"
-    cmp "${MTX_TEST_DATA_DIR}/Mat$f" tmp.$$.x || error "ZUK with trivial orbits: wrong result"
+    zuk -Q "${MTX_TEST_DATA_DIR}/Mat$f" orbs x || error "ZUK failed"
+    cmp "${MTX_TEST_DATA_DIR}/Mat$f" x || error "ZUK with trivial orbits: wrong result"
 done
 
-cat > tmp.$$.orbs.txt << EOT
+cat > orbs.txt << EOT
 integer-matrix rows=1 cols=26
 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 0 23
 integer-matrix rows=1 cols=24
 2 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2
 EOT
-zcv -Q tmp.$$.orbs.txt tmp.$$.orbs || error "ZCV failed"
+zcv -Q orbs.txt orbs || error "ZCV failed"
 for f in 2 5 9 25 67 125 256 ; do
-    zuk -Q "${MTX_TEST_DATA_DIR}/Mat$f" tmp.$$.orbs tmp.$$.x$f || error "ZUK failed"
-    zpr tmp.$$.x$f tmp.$$.x$f.txt 
-    cmp tmp.$$.x$f.txt "${MTX_TESTCASE_DIR}/x$f.txt.expected"
+    zuk -Q "${MTX_TEST_DATA_DIR}/Mat$f" orbs x$f || error "ZUK failed"
+    zpr x$f x$f.txt 
+    cmp x$f.txt "${MTX_TESTCASE_DIR}/x$f.txt.expected"
 done
 
-# Clean up
-rm -f tmp.$$.*
diff --git a/tests/0200/run b/tests/0200/run
--- a/tests/0200/run
+++ b/tests/0200/run
@@ -1,33 +1,47 @@
 echo "0200 - Submodules of m11"
 
+#set -x
 . ../tests/common.sh
 
-cp "${MTX_TEST_DATA_DIR}/m11.1" tmp.$$.m11.1
-cp "${MTX_TEST_DATA_DIR}/m11.2" tmp.$$.m11.2
 
-chop -Q tmp.$$.m11 || error "CHOP failed"
-cmp tmp.$$.m11.cfinfo "${MTX_TESTCASE_DIR}/cfinfo_after_chop.expected"
+cp "${MTX_TEST_DATA_DIR}/m11.1" m11.1
+cp "${MTX_TEST_DATA_DIR}/m11.2" m11.2
 
-pwkond -Qt tmp.$$.m11 || error "PWKOND failed"
-cmp tmp.$$.m11.cfinfo "${MTX_TESTCASE_DIR}/cfinfo_after_pwkond.expected"
+chop -Q m11 || error "CHOP failed"
+compareWithReference m11.cfinfo cfinfo_after_chop.expected
 
-mkcycl -Q tmp.$$.m11 || error "MKCYCL FAILED"
+pwkond -Qt m11 || error "PWKOND failed"
+compareWithReference m11.cfinfo cfinfo_after_pwkond.expected
 
-mkinc -Q tmp.$$.m11 || error "MKINC FAILED"
-cmp tmp.$$.m11.mnt "${MTX_TESTCASE_DIR}/mnt.expected"
+mkcycl -Q m11 || error "MKCYCL FAILED"
 
-mkdotl -Q tmp.$$.m11 || error "MKDOTL FAILED"
-cmp tmp.$$.m11.cfinfo "${MTX_TESTCASE_DIR}/cfinfo_after_mkdotl.expected"
+mkinc -Q m11 || error "MKINC FAILED"
+compareWithReference m11.mnt
 
-mksub -Q tmp.$$.m11 || error "MKSUB FAILED"
-cmp tmp.$$.m11.out "${MTX_TESTCASE_DIR}/m11.out.expected"
-cmp tmp.$$.m11.lat "${MTX_TESTCASE_DIR}/m11.lat.expected"
-cmp tmp.$$.m11.gra "${MTX_TESTCASE_DIR}/m11.gra.expected"
+mkdotl -Q m11 || error "MKDOTL FAILED"
+compareWithReference m11.cfinfo cfinfo_after_mkdotl.expected
 
-soc -Q tmp.$$.m11 || error "SOC failed"
-rad -Q tmp.$$.m11 || error "RAD failed"
-cmp tmp.$$.m11.cfinfo "${MTX_TESTCASE_DIR}/cfinfo_after_socrad.expected"
+mksub -Q m11 || error "MKSUB FAILED"
+compareWithReference m11.out
+compareWithReference m11.lat
+compareWithReference m11.gra
 
+soc -Q m11 || error "SOC failed"
+rad -Q m11 || error "RAD failed"
+compareWithReference m11.cfinfo cfinfo_after_socrad.expected
 
-# Clean up
-rm -f tmp.$$.* 
+# Generate one submodule
+genmod -Q m11 13
+compareBinaryWithReference m11.s13
+
+# Check that it's actually a submodule
+for gen in 1 2; do
+   zmu m11.s13 m11.$gen img
+   zcl m11.s13 img imgcl imgops
+   zef -Q imgcl m11.s13.img.$gen
+   compareBinaryWithReference m11.s13.img.$gen
+done
+
+# Generate one mountain
+genmod -Q -m m11 7
+compareBinaryWithReference m11.m7
diff --git a/tests/0213/run b/tests/0213/run
--- a/tests/0213/run
+++ b/tests/0213/run
@@ -2,12 +2,12 @@ echo "0213 - Endomorphisms of m11 (dim = 112)"
 
 . ../tests/common.sh
 
-cp "${MTX_TEST_DATA_DIR}/m11.1" tmp.$$.m11.1
-cp "${MTX_TEST_DATA_DIR}/m11.2" tmp.$$.m11.2
-chop -Q -g 2 tmp.$$.m11 || error "CHOP failed"
-pwkond -Qt tmp.$$.m11 || error "PWKOND failed"
-mkhom -Qts tmp.$$.m11 tmp.$$.m11 tmp.$$.end ||  error "MKHOM failed"
-if [ ! -r tmp.$$.end.4 -o -r tmp.$$.end.5 ]; then error "Wrong number of endomorphisms"; fi
+cp "${MTX_TEST_DATA_DIR}/m11.1" m11.1
+cp "${MTX_TEST_DATA_DIR}/m11.2" m11.2
+chop -Q -g 2 m11 || error "CHOP failed"
+pwkond -Qt m11 || error "PWKOND failed"
+mkhom -Qts m11 m11 end ||  error "MKHOM failed"
+if [ ! -r end.4 -o -r end.5 ]; then error "Wrong number of endomorphisms"; fi
 
 compareBinaryWithReference end.1
 compareBinaryWithReference end.2
@@ -16,12 +16,9 @@ compareBinaryWithReference end.4
 
 for g in 1 2; do
    for e in 1 2 3 4; do
-       zmu tmp.$$.m11.std.$g tmp.$$.end.$e tmp.$$.a
-       zmu tmp.$$.end.$e tmp.$$.m11.std.$g tmp.$$.b
-       cmp tmp.$$.a tmp.$$.b || error "Endomorphism does not commute with generators"
+       zmu m11.std.$g end.$e a
+       zmu end.$e m11.std.$g b
+       cmp a b || error "Endomorphism does not commute with generators"
    done
 done
 
-# Clean up
-# --------
-rm -f tmp.$$.*
diff --git a/tests/0214/run b/tests/0214/run
--- a/tests/0214/run
+++ b/tests/0214/run
@@ -2,12 +2,12 @@ echo "0214 - Endomorphisms of ac (dim = 167)"
 
 . ../tests/common.sh
 
-cp "${MTX_TEST_DATA_DIR}/ac.1" tmp.$$.ac.1
-cp "${MTX_TEST_DATA_DIR}/ac.2" tmp.$$.ac.2
-chop -Q -g 2 tmp.$$.ac || error "CHOP failed"
-pwkond -Qt tmp.$$.ac || error "PWKOND failed"
-mkhom -Q -t -s tmp.$$.ac tmp.$$.ac tmp.$$.end ||  error "MKHOM failed"
-if [ ! -r tmp.$$.end.8 -o -r tmp.$$.end.9 ]; then error "Wrong number of endomorphisms"; fi
+cp "${MTX_TEST_DATA_DIR}/ac.1" ac.1
+cp "${MTX_TEST_DATA_DIR}/ac.2" ac.2
+chop -Q -g 2 ac || error "CHOP failed"
+pwkond -Qt ac || error "PWKOND failed"
+mkhom -Q -t -s ac ac end ||  error "MKHOM failed"
+if [ ! -r end.8 -o -r end.9 ]; then error "Wrong number of endomorphisms"; fi
 
 compareBinaryWithReference end.1
 compareBinaryWithReference end.2
@@ -20,11 +20,9 @@ compareBinaryWithReference end.8
 
 for g in 1 2; do
    for e in 1 2 3 4 5 6 7 8; do
-       zmu tmp.$$.ac.std.$g tmp.$$.end.$e tmp.$$.a
-       zmu tmp.$$.end.$e tmp.$$.ac.std.$g tmp.$$.b
-       cmp tmp.$$.a tmp.$$.b || error "Endomorphism does not commute with generators"
+       zmu ac.std.$g end.$e a
+       zmu end.$e ac.std.$g b
+       cmp a b || error "Endomorphism does not commute with generators"
    done
 done
 
-# Clean up
-rm -f tmp.$$.*
